# .woodpecker.yml

when:
  event: tag

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true
      lfs: false

steps:
  build:
    image: tectogen/build-old-ubuntu
    commands:
      - cmake -Btectogen-linux
      - cmake --build tectogen-linux
      - patchelf --replace-needed libGLEW.so.2.1 libGLEW.so tectogen-linux/bin/tectogen # https://abi-laboratory.pro/index.php?view=objects_report&l=glew&v1=2.1.0&v2=2.2.0
      - tar czvf tectogen-linux.tar.gz tectogen-linux/bin tectogen-linux/share
      - PATH="/mxe/usr/bin/:$PATH" x86_64-w64-mingw32.static-cmake -Btectogen-windows
      - PATH="/mxe/usr/bin/:$PATH" x86_64-w64-mingw32.static-cmake --build tectogen-windows
      - 7z a -tzip tectogen-windows.zip tectogen-windows/bin tectogen-windows/share
  publish:
    image: woodpeckerci/plugin-gitea-release
    when:
      event: tag
    settings:
      base_url: https://codeberg.org
      files:
        - "tectogen-linux.tar.gz"
        - "tectogen-windows.zip"
      prerelease: true
      file-exists: fail
      api_key:
        from_secret: codeberg_access_token
      target: main
      title: tectogen ${CI_COMMIT_TAG}