# .woodpecker.yml

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true
      lfs: false

steps:
  main:
    image: tectogen/build-old-ubuntu

    commands:
      - cmake -Bbuild
      - cmake --build build
